# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
       t=$(git describe --tags `git rev-list --tags --max-count=1`)

       # get current commit hash for tag
       commit=$(git rev-parse HEAD)

       # if there are none, start tags at 0.0.0
       if [ -z "$t" ]
       then
           log=$(git log --pretty=oneline)
           t=0.0.0
       else
           log=$(git log $t..HEAD --pretty=oneline)
       fi

       # get commit logs and determine home to bump the version
       # supports #major, #minor, #patch (anything else will be 'minor')
       case "$log" in
           *#major* ) new=$(semver bump major $t);;
           *#patch* ) new=$(semver bump patch $t);;
           * ) new=$(semver bump minor $t);;
       esac
       {
        "ref": "refs/tags/$new",
        "sha": "$commit"
       }
       EOF
